version: "3.5"
services:
  grafana:
    image: grafana/grafana:6.2.4
    hostname: grafana
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    # ports:
    #   - "3000:3000"
    volumes:
      - "/var/docker/grafana/data:/var/lib/grafana"
      - "/var/docker/grafana/log:/var/log/grafana"
      - "/var/docker/grafana/conf/grafana.ini:/etc/grafana/grafana.ini:ro"
    environment:
      GF_SECURITY_ADMIN_PASSWORD_FILE: /run/secrets/admin_password
    user: "1000"
    networks:
      - online
networks:
  online:
    external: true
    name: online
